name: deploy_to_gh_pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies and build
        run: |
          npm install
          npm run build-only
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          enable_jekyll: false
          keep_files: true
          verbose: true
          clean: true
          allow_empty_commit: false
          force_orphan: false
          silent: false
          # fqdn: example.com # replace with your domain name
          skip_ci: false
          remove_previous_cache: true
          cache_enabled: true
          cache_dir_name: ".cache"
